### ISSUE TITLE
bug: Unable to find a binary for release "latest". 

### ISSUE THREAD

**Issue by markitosgv** [sensiolabs/minify-bundle#18]
When compiling assets throws this error. Im using symfony 7.1 and php 8.3 in docker environment with debian.

**Comment by smnandre** [comment]
Hello @markitosgv,

could you tell me what os / architecture you are on ?

**Comment by smnandre** [comment]
@markitosgv 

wow i did not read your messagee correctly i'm so sorry... 😨 

Can you share the result of 

```
php bin/console minify:install -vvv
```

**Comment by rglozman** [comment]
Here are the results of executing the requested command:
```
PS D:\XAMPP\htdocs\PROJECT> php bin/console minify:install -vvv
22:26:02 INFO      [http_client] Request: "GET https://api.github.com/repos/tdewolff/minify/releases/latest"
22:26:03 INFO      [http_client] Response: "200 https://api.github.com/repos/tdewolff/minify/releases/latest"

In MinifyInstaller.php line 123:

  [Sensiolabs\MinifyBundle\Exception\InstallException]  
  Unable to find a binary for release "latest".


Exception trace:
  at D:\XAMPP\htdocs\PROJECT\vendor\sensiolabs\minify-bundle\src\MinifyInstaller.php:123
 Sensiolabs\MinifyBundle\MinifyInstaller->getReleaseAsset() at D:\XAMPP\htdocs\PROJECT\vendor\sensiolabs\minify-bundle\src\MinifyInstaller.php:66
 Sensiolabs\MinifyBundle\MinifyInstaller->download() at D:\XAMPP\htdocs\PROJECT\vendor\sensiolabs\minify-bundle\src\MinifyInstaller.php:51
 Sensiolabs\MinifyBundle\MinifyInstaller->install() at D:\XAMPP\htdocs\PROJECT\vendor\sensiolabs\minify-bundle\src\Command\MinifyInstallCommand.php:72
 Sensiolabs\MinifyBundle\Command\MinifyInstallCommand->execute() at D:\XAMPP\htdocs\PROJECT\vendor\symfony\console\Command\Command.php:279
 Symfony\Component\Console\Command\Command->run() at D:\XAMPP\htdocs\PROJECT\vendor\symfony\console\Application.php:1047
 Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand() at D:\XAMPP\htdocs\PROJECT\vendor\symfony\console\Application.php:316
 Symfony\Component\Console\Application->doRun() at D:\XAMPP\htdocs\PROJECT\vendor\symfony\framework-bundle\Console\Application.php:77
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at D:\XAMPP\htdocs\PROJECT\vendor\symfony\console\Application.php:167
 Symfony\Component\Console\Application->run() at D:\XAMPP\htdocs\PROJECT\vendor\symfony\runtime\Runner\Symfony\ConsoleApplicationRunner.php:49
 Symfony\Component\Runtime\Runner\Symfony\ConsoleApplicationRunner->run() at D:\XAMPP\htdocs\PROJECT\vendor\autoload_runtime.php:29
 require_once() at D:\XAMPP\htdocs\PROJECT\bin\console:15
```

**Comment by smnandre** [comment]
Hi @rglozman : could you test [this PR](https://github.com/sensiolabs/minify-bundle/pull/20) and tell me if everything is working on Windows ? Not something easy to test on my side

**Comment by rglozman** [comment]
Thank you for the quick turn around! I had to make a few changes to make it work: [Pull Request](https://github.com/smnandre/minify-bundle/pull/1)

However, there is now a different error, probably worth opening a different ticket for:
```
In Minify.php line 42:

  [Sensiolabs\MinifyBundle\Exception\RuntimeException]  
  Minify error 1: "General error".


Exception trace:
  at D:\XAMPP\htdocs\PROJECT\vendor\sensiolabs\minify-bundle\src\Minify.php:42
 Sensiolabs\MinifyBundle\Minify->minify() at D:\XAMPP\htdocs\PROJECT\vendor\sensiolabs\minify-bundle\src\Minifier\TraceableMinifier.php:39
 Sensiolabs\MinifyBundle\Minifier\TraceableMinifier->minify() at D:\XAMPP\htdocs\PROJECT\vendor\sensiolabs\minify-bundle\src\AssetMapper\MinifierCompiler.php:66
 Sensiolabs\MinifyBundle\AssetMapper\MinifierCompiler->compile() at D:\XAMPP\htdocs\PROJECT\vendor\symfony\asset-mapper\AssetMapperCompiler.php:40
 Symfony\Component\AssetMapper\AssetMapperCompiler->compile() at D:\XAMPP\htdocs\PROJECT\vendor\symfony\asset-mapper\Factory\MappedAssetFactory.php:109
 Symfony\Component\AssetMapper\Factory\MappedAssetFactory->compileContent() at D:\XAMPP\htdocs\PROJECT\vendor\symfony\asset-mapper\Factory\MappedAssetFactory.php:50
 Symfony\Component\AssetMapper\Factory\MappedAssetFactory->createMappedAsset() at D:\XAMPP\htdocs\PROJECT\vendor\symfony\asset-mapper\Factory\CachedMappedAssetFactory.php:43
 Symfony\Component\AssetMapper\Factory\CachedMappedAssetFactory->createMappedAsset() at D:\XAMPP\htdocs\PROJECT\vendor\symfony\asset-mapper\AssetMapper.php:41
 Symfony\Component\AssetMapper\AssetMapper->getAsset() at D:\XAMPP\htdocs\PROJECT\vendor\symfony\asset-mapper\AssetMapper.php:47
 Symfony\Component\AssetMapper\AssetMapper->allAssets() at D:\XAMPP\htdocs\PROJECT\vendor\symfony\asset-mapper\Command\AssetMapperCompileCommand.php:109
 Symfony\Component\AssetMapper\Command\AssetMapperCompileCommand->createManifestAndWriteFiles() at D:\XAMPP\htdocs\PROJECT\vendor\symfony\asset-mapper\Command\AssetMapperCompileCommand.php:77
 Symfony\Component\AssetMapper\Command\AssetMapperCompileCommand->execute() at D:\XAMPP\htdocs\PROJECT\vendor\symfony\console\Command\Command.php:279
 Symfony\Component\Console\Command\Command->run() at D:\XAMPP\htdocs\PROJECT\vendor\symfony\console\Application.php:1047
 Symfony\Component\Console\Application->doRunCommand() at D:\XAMPP\htdocs\PROJECT\vendor\symfony\framework-bundle\Console\Application.php:123
 Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand() at D:\XAMPP\htdocs\PROJECT\vendor\symfony\console\Application.php:316
 Symfony\Component\Console\Application->doRun() at D:\XAMPP\htdocs\PROJECT\vendor\symfony\framework-bundle\Console\Application.php:77
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at D:\XAMPP\htdocs\PROJECT\vendor\symfony\console\Application.php:167
 Symfony\Component\Console\Application->run() at D:\XAMPP\htdocs\PROJECT\vendor\symfony\runtime\Runner\Symfony\ConsoleApplicationRunner.php:49
 Symfony\Component\Runtime\Runner\Symfony\ConsoleApplicationRunner->run() at D:\XAMPP\htdocs\PROJECT\vendor\autoload_runtime.php:29
 require_once() at D:\XAMPP\htdocs\PROJECT\bin\console:15

asset-map:compile
```

**Comment by smnandre** [comment]
Could you add some verbosity here ? 

```
php bin/console asset-map:compile -vvv 
```

COuld you maybe also try to minify manually a CSS file per example with the minify:asset command  ? (see in the README for an example)

**Comment by rglozman** [comment]
Here it is ran on a single file containing the following code:
```
console.log("TEST");
```

Error dump with verbosity:
```
PS D:\XAMPP\htdocs\PROJECT> php bin/console minify:asset -vvv .\assets\test.js
02:48:16 DEBUG     [assets] Minify command input: 0.0 kB
[
  "inputSize" => 0.0,
  "input" => "console.log("TEST");"
]

In Minify.php line 42:

  [Sensiolabs\MinifyBundle\Exception\RuntimeException]  
  Minify error 1: "General error".


Exception trace:
  at D:\XAMPP\htdocs\PROJECT\vendor\sensiolabs\minify-bundle\src\Minify.php:42
 Sensiolabs\MinifyBundle\Minify->minify() at D:\XAMPP\htdocs\PROJECT\vendor\sensiolabs\minify-bundle\src\Minifier\TraceableMinifier.php:39
 Sensiolabs\MinifyBundle\Minifier\TraceableMinifier->minify() at D:\XAMPP\htdocs\PROJECT\vendor\sensiolabs\minify-bundle\src\Command\MinifyAssetCommand.php:109
 Sensiolabs\MinifyBundle\Command\MinifyAssetCommand->execute() at D:\XAMPP\htdocs\PROJECT\vendor\symfony\console\Command\Command.php:279
 Symfony\Component\Console\Command\Command->run() at D:\XAMPP\htdocs\PROJECT\vendor\symfony\console\Application.php:1047
 Symfony\Component\Console\Application->doRunCommand() at D:\XAMPP\htdocs\PROJECT\vendor\symfony\framework-bundle\Console\Application.php:123
 Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand() at D:\XAMPP\htdocs\PROJECT\vendor\symfony\console\Application.php:316
 Symfony\Component\Console\Application->doRun() at D:\XAMPP\htdocs\PROJECT\vendor\symfony\framework-bundle\Console\Application.php:77
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at D:\XAMPP\htdocs\PROJECT\vendor\symfony\console\Application.php:167
 Symfony\Component\Console\Application->run() at D:\XAMPP\htdocs\PROJECT\vendor\symfony\runtime\Runner\Symfony\ConsoleApplicationRunner.php:49
 Symfony\Component\Runtime\Runner\Symfony\ConsoleApplicationRunner->run() at D:\XAMPP\htdocs\PROJECT\vendor\autoload_runtime.php:29
 require_once() at D:\XAMPP\htdocs\PROJECT\bin\console:15

minify:asset [-t|--type TYPE] [--] <input> [<output>]
```

I was also able to generate the following error with a css file:
```
In Minify.php line 38:

  [Sensiolabs\MinifyBundle\Exception\RuntimeException]
  Error during minify command: Notice: fwrite(): Write of 11307 bytes failed with errno=32 Broken pipe  


Exception trace:
  at D:\XAMPP\htdocs\PROJECT\vendor\sensiolabs\minify-bundle\src\Minify.php:38
 Sensiolabs\MinifyBundle\Minify->minify() at D:\XAMPP\htdocs\PROJECT\vendor\sensiolabs\minify-bundle\src\Minifier\TraceableMinifier.php:39
 Sensiolabs\MinifyBundle\Minifier\TraceableMinifier->minify() at D:\XAMPP\htdocs\PROJECT\vendor\sensiolabs\minify-bundle\src\Command\MinifyAssetCommand.php:109
 Sensiolabs\MinifyBundle\Command\MinifyAssetCommand->execute() at D:\XAMPP\htdocs\PROJECT\vendor\symfony\console\Command\Command.php:279
 Symfony\Component\Console\Command\Command->run() at D:\XAMPP\htdocs\PROJECT\vendor\symfony\console\Application.php:1047
 Symfony\Component\Console\Application->doRunCommand() at D:\XAMPP\htdocs\PROJECT\vendor\symfony\framework-bundle\Console\Application.php:123
 Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand() at D:\XAMPP\htdocs\PROJECT\vendor\symfony\console\Application.php:316
 Symfony\Component\Console\Application->doRun() at D:\XAMPP\htdocs\PROJECT\vendor\symfony\framework-bundle\Console\Application.php:77
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at D:\XAMPP\htdocs\PROJECT\vendor\symfony\console\Application.php:167
 Symfony\Component\Console\Application->run() at D:\XAMPP\htdocs\PROJECT\vendor\symfony\runtime\Runner\Symfony\ConsoleApplicationRunner.php:49
 Symfony\Component\Runtime\Runner\Symfony\ConsoleApplicationRunner->run() at D:\XAMPP\htdocs\PROJECT\vendor\autoload_runtime.php:29
 require_once() at D:\XAMPP\htdocs\PROJECT\bin\console:15

In AbstractPipes.php line 126:

  [ErrorException]
  Notice: fwrite(): Write of 11307 bytes failed with errno=32 Broken pipe  


Exception trace:
  at D:\XAMPP\htdocs\PROJECT\vendor\symfony\process\Pipes\AbstractPipes.php:126
 Symfony\Component\Process\Pipes\AbstractPipes->write() at D:\XAMPP\htdocs\PROJECT\vendor\symfony\process\Pipes\WindowsPipes.php:136
 Symfony\Component\Process\Pipes\WindowsPipes->readAndWrite() at D:\XAMPP\htdocs\PROJECT\vendor\symfony\process\Process.php:1417
 Symfony\Component\Process\Process->readPipes() at D:\XAMPP\htdocs\PROJECT\vendor\symfony\process\Process.php:1342
 Symfony\Component\Process\Process->updateStatus() at D:\XAMPP\htdocs\PROJECT\vendor\symfony\process\Process.php:389
 Symfony\Component\Process\Process->start() at D:\XAMPP\htdocs\PROJECT\vendor\symfony\process\Process.php:249
 Symfony\Component\Process\Process->run() at D:\XAMPP\htdocs\PROJECT\vendor\sensiolabs\minify-bundle\src\Minify.php:36
 Sensiolabs\MinifyBundle\Minify->minify() at D:\XAMPP\htdocs\PROJECT\vendor\sensiolabs\minify-bundle\src\Minifier\TraceableMinifier.php:39
 Sensiolabs\MinifyBundle\Minifier\TraceableMinifier->minify() at D:\XAMPP\htdocs\PROJECT\vendor\sensiolabs\minify-bundle\src\Command\MinifyAssetCommand.php:109
 Sensiolabs\MinifyBundle\Command\MinifyAssetCommand->execute() at D:\XAMPP\htdocs\PROJECT\vendor\symfony\console\Command\Command.php:279
 Symfony\Component\Console\Command\Command->run() at D:\XAMPP\htdocs\PROJECT\vendor\symfony\console\Application.php:1047
 Symfony\Component\Console\Application->doRunCommand() at D:\XAMPP\htdocs\PROJECT\vendor\symfony\framework-bundle\Console\Application.php:123
 Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand() at D:\XAMPP\htdocs\PROJECT\vendor\symfony\console\Application.php:316
 Symfony\Component\Console\Application->doRun() at D:\XAMPP\htdocs\PROJECT\vendor\symfony\framework-bundle\Console\Application.php:77
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at D:\XAMPP\htdocs\PROJECT\vendor\symfony\console\Application.php:167
 Symfony\Component\Console\Application->run() at D:\XAMPP\htdocs\PROJECT\vendor\symfony\runtime\Runner\Symfony\ConsoleApplicationRunner.php:49
 Symfony\Component\Runtime\Runner\Symfony\ConsoleApplicationRunner->run() at D:\XAMPP\htdocs\PROJECT\vendor\autoload_runtime.php:29
 require_once() at D:\XAMPP\htdocs\PROJECT\bin\console:15

minify:asset [-t|--type TYPE] [--] <input> [<output>]

PHP Fatal error:  Uncaught ErrorException: Notice: fwrite(): Write of 11307 bytes failed with errno=22 Invalid argument in D:\XAMPP\htdocs\PROJECT\vendor\symfony\process\Pipes\AbstractPipes.php:126
Stack trace:
#0 D:\XAMPP\htdocs\PROJECT\vendor\symfony\process\Pipes\WindowsPipes.php(136): Symfony\Component\Process\Pipes\AbstractPipes->write()
#1 D:\XAMPP\htdocs\PROJECT\vendor\symfony\process\Process.php(1417): Symfony\Component\Process\Pipes\WindowsPipes->readAndWrite(false, true)
#2 D:\XAMPP\htdocs\PROJECT\vendor\symfony\process\Process.php(1342): Symfony\Component\Process\Process->readPipes(false, true)
#3 D:\XAMPP\htdocs\PROJECT\vendor\symfony\process\Process.php(865): Symfony\Component\Process\Process->updateStatus(false)
#4 D:\XAMPP\htdocs\PROJECT\vendor\symfony\process\Process.php(911): Symfony\Component\Process\Process->isRunning()
#5 D:\XAMPP\htdocs\PROJECT\vendor\symfony\process\Process.php(215): Symfony\Component\Process\Process->stop(0.0)
#6 [internal function]: Symfony\Component\Process\Process->__destruct()
#7 {main}
  thrown in D:\XAMPP\htdocs\PROJECT\vendor\symfony\process\Pipes\AbstractPipes.php on line 126

Fatal error: Uncaught ErrorException: Notice: fwrite(): Write of 11307 bytes failed with errno=22 Invalid argument in D:\XAMPP\htdocs\PROJECT\vendor\symfony\process\Pipes\AbstractPipes.php:126
Stack trace:
#0 D:\XAMPP\htdocs\PROJECT\vendor\symfony\process\Pipes\WindowsPipes.php(136): Symfony\Component\Process\Pipes\AbstractPipes->write()
#1 D:\XAMPP\htdocs\PROJECT\vendor\symfony\process\Process.php(1417): Symfony\Component\Process\Pipes\WindowsPipes->readAndWrite(false, true)
#2 D:\XAMPP\htdocs\PROJECT\vendor\symfony\process\Process.php(1342): Symfony\Component\Process\Process->readPipes(false, true)
#3 D:\XAMPP\htdocs\PROJECT\vendor\symfony\process\Process.php(865): Symfony\Component\Process\Process->updateStatus(false)
#4 D:\XAMPP\htdocs\PROJECT\vendor\symfony\process\Process.php(911): Symfony\Component\Process\Process->isRunning()
#5 D:\XAMPP\htdocs\PROJECT\vendor\symfony\process\Process.php(215): Symfony\Component\Process\Process->stop(0.0)
#6 [internal function]: Symfony\Component\Process\Process->__destruct()
#7 {main}
  thrown in D:\XAMPP\htdocs\PROJECT\vendor\symfony\process\Pipes\AbstractPipes.php on line 126

```

**Comment by mehdibo** [comment]
I have the same issue, the reason is that I am running it inside Docker, and the following:

```
<?php

var_dump(php_uname('m'));  // string(7) "aarch64"       
```
Doesn't exist in the github releases' assets
